<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">
      <ul class="mainnav">
        <li><a href="<?php echo BASE_URL;?>principal"><i class="icon-file"></i><span>Proyectos</span> </a> </li>
        <li><a href="<?php echo BASE_URL;?>inventario"><i class="icon-list-alt"></i><span>Inventario</span> </a> </li>
        <li><a href="<?php echo BASE_URL;?>estadisticas"><i class="icon-bar-chart"></i><span>Estadisticas</span> </a></li>
        <li class="active"><a href="<?php echo BASE_URL;?>reportes"><i class="icon-copy"></i><span>Reportes</span> </a> </li>
        <li><a href="#"><i class="icon-code"></i><span>Otros</span> </a> </li>
      </ul>
    </div>
    <!-- /container --> 
  </div>
  <!-- /subnavbar-inner --> 
</div>


<div class="container">
<div class="col-md-12">
	AREA DE TRABAJO
</div>
</div>
		
		
		

