<div class="col-xs-12">


	<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
              <div><h3 class="title1"> <center> RegistrateX</center></h3></div>
				<form>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Cedula</label>
				    <input type="text" class="form-control" id="cedula" name="cedula" placeholder="Cedula">
				  </div>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Nombres</label>
				    <input type="text" class="form-control" id="nombres" name="nombres" placeholder="Nombres">
				  </div>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Apellidos</label>
				    <input type="text" class="form-control" id="apellidos" name="apellidos" placeholder="Apellidos">
				  </div>
				   <div class="form-group">
				    <label for="exampleInputEmail1">Fecha de nacimiento</label>
				    <input type="text" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" placeholder="DD/MM/AA">
				  </div>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Correo</label>
				    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Correo">
				  </div>
				    <div class="form-group">
				    <label for="exampleInputEmail1">Login</label>
				    <input type="email" class="form-control" id="login" name="login" placeholder="Login">
				  </div>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Password</label>
				    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
				  </div>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Confirmar Password</label>
				    <input type="password" class="form-control" id="confirmar_password" name="confirmar_password" placeholder="Confirmar Password">
				  </div>
				  
				  <center> <button type="submit" class="btn btn-default">Registrarse</button> </center>
				</form> 
            
        </div>
    </div>
</div>

</div>